# Generated by Django 4.2.3 on 2023-07-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(related_name='articles', to='test.publication'),
        ),
    ]
