name: NESCS CD

on:
  workflow_run:
    workflows: [ workflow1 ]
    types:
      - completed
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Hello world 👋"
