name: NESCS CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
  deploy:
    runs-on: ubuntu-latest
    needs: test
#    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
#      - name: Build package
#        run: |
#          sh ../../nesc/rebuild.sh
      - name: Deploy package
        run: |
            ls -la